PCBTracker/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.auth import views as auth_views

from tracker import views

admin.autodiscover()

urlpatterns = [
    # View (single) boards
    re_path(r'^board/(?P<class_id>\d+)/$', views.boards, name='board'),
    re_path(r'^board/detail/(?P<board_id>\d+)/$', views.board, name='board-details'),
    re_path(r'^board/new/(?P<class_id>\d+)/$', views.add_board, name='board-new'),
    re_path(r'^board/edit/(?P<board_id>\d+)/$', views.edit_board, name='board-edit'),
    re_path(r'^board/export_patches/(?P<status_id>\d+)/$', views.export_patches, name='patches-export'),
    re_path(r'^board/$', views.boards, name='boards'),

    # View (single) patches
    re_path(r'^patch/(?P<patch_id>\d+)/$', views.patch, name='patch'),
    re_path(r'^patch/new/(?P<class_id>\d+)/$', views.add_patch, name='patch-new'),
    re_path(r'^patch/edit/(?P<patch_id>\d+)/$', views.edit_patch, name='patch-edit'),

    # Add new project
    re_path(r'^project/new/$', views.add_project, name='project-new'),
    re_path(r'^project/edit/(?P<project_id>\d+)/$', views.edit_project, name='project-edit'),

    # Add new boardclass
    re_path(r'^boardclass/new/(?P<project_id>\d+)/$', views.add_boardclass, name='boardclass-new'),
    re_path(r'^boardclass/edit/(?P<class_id>\d+)/$', views.edit_boardclass, name='boardclass-edit'),

    # Add new event for a board
    re_path(r'^event/new/(?P<board_id>\d+)/$', views.add_event, name='event-new'),

    # Claim board (as user) or change location
    re_path(r'^claim/(?P<board_id>\d+)/$', views.claim_board, name='claim'),
    re_path(r'^newlocation/(?P<board_id>\d+)/$', views.add_location, name='location-new'),

    # Search function with raw input
    re_path(r'^search_raw/(?P<searchstring>.+)$', views.raw_search, name='search-raw'),

    # Search function
    re_path(r'^search/$', views.search, name='search'),

    # Login and registration
    re_path(r'^register/$', views.do_register, name='register'),
    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(template_name='login.html' ), name='accounts-login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(template_name='logout.html' ), name='accounts-logout'),

    re_path(r'login/$', auth_views.LoginView.as_view(template_name='login.html' ), name='login'),
    re_path(r'logout/$', auth_views.LogoutView.as_view(template_name='logout.html' ), name='logout'),

    # Uncomment the next line to enable the admin:
    re_path(r'admin/', admin.site.urls),

    # Fall through to Main Page
    re_path(r'main/$', views.reset_index, name='main'),

    re_path(r'^', views.index, name='index')
]

PCBTracker/forms.py
from django import forms
from django.core import validators

class MantisField(forms.CharField):
    def __init__(self, *args, **kwargs):
        super(MantisField, self).__init__(*args, **kwargs)
        self.validators.append(validators.RegexValidator(
            regex = r'^[\d\n\r, ]*$',
            message = 'Please enter only numbers, separated by commas, newlines or spaces.',
        ))

class RegisterForm(forms.Form):
    username = forms.CharField(label='Username*')
    email = forms.EmailField(label='E-Mail*')
    firstname = forms.CharField(label='First name', required=False)
    lastname = forms.CharField(label='Last name', required=False)
    password = forms.CharField(label='Password*', widget=forms.PasswordInput(render_value=False))
    password2 = forms.CharField(label='Password (again)*', widget=forms.PasswordInput(render_value=False))

class ProjectForm(forms.Form):
    name = forms.CharField(label='Project-Nr')
    desc = forms.CharField(label='Name', required=False)

class BoardClassForm(forms.Form):
    name = forms.CharField(label='Name')
    desc = forms.CharField(label='Description', required=False, widget=forms.Textarea())
    productnr = forms.CharField(label='Product-ID')
    revision = forms.CharField(label='Revision', required=False)

class BoardForm(forms.Form):
    csnr = forms.CharField(label='Internal ID')
    comment = forms.CharField(label='Comment', widget=forms.Textarea(), required=False)
    serial_top = forms.CharField(label='Top serial', required=False)
    serial_bottom = forms.CharField(label='Bottom serial', required=False)
    defect = forms.BooleanField(label='Defect?', required=False)
    swversion = forms.CharField(label='SW version', required=False)
    attachment = forms.FileField(widget=forms.FileInput(), required=False)

class PatchForm(forms.Form):
    name = forms.CharField(max_length=30)
    desc = forms.CharField(max_length=2000, widget=forms.Textarea(), required=False)
    why = forms.CharField(max_length=2000, widget=forms.Textarea(), required=False)
    mandatory = forms.NullBooleanField('Mandatory')
    mantis = MantisField(max_length=2000, widget=forms.Textarea(), required=False)
    attachment = forms.FileField(widget=forms.FileInput(), required=False)

class EventForm(forms.Form):
    desc = forms.CharField(max_length=2000, widget=forms.Textarea(), required=True, label="Description")

class LocationForm(forms.Form):
    location = forms.CharField(max_length=200, required=True, label="Location")

class SearchForm(forms.Form):
    searchstring = forms.CharField(max_length=200, required=True, label="Search-pattern")
    search_boardname = forms.BooleanField(label="Search boardname?", initial=True)
    search_projectname = forms.BooleanField(label="Search projectname?", initial=True)
    search_serial = forms.BooleanField(label="Search serial numbers?", initial=True)
    search_productnr = forms.BooleanField(label="Search product-nr?", initial=True)
    search_patchnr = forms.BooleanField(label="Search patch-nr?", initial=True)

PCBTracker/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.files.base import ContentFile
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from PCBTracker.helpers import *
from PCBTracker.models import *
from PCBTracker.forms import *

import re


def reset_index(request):
    request.session['last_boardclass'] = None
    return HttpResponseRedirect(reverse(index))


def main(request):
    return my_render_to_response('base_skeleton.html', { }, request)


def index(request):
    last_boardclass = request.session.get('last_boardclass', None)
    if last_boardclass:
        return boards(request, last_boardclass)

    all_projects = []
    projects = Project.objects.all().order_by("name")

    for p in projects:
        project_boards = BoardClass.objects.filter(projectid=p.id)
        all_projects.append({'project': p, 'boards': project_boards})

    return my_render_to_response('tracker/index.html', {
        'all_projects' : all_projects,
    }, request)


def boards(request, class_id=''):
    boardclass = BoardClass.objects.get(id=class_id)
    boards = Board.objects.filter(classid=class_id).order_by('csnr')

    request.session['last_boardclass'] = class_id

    patchdescs = get_patchdescs(class_id)

    for p in patchdescs:
        entries = p['desc'].mantis.split()

        for split_character in [" ", ",", "\n", "\r"]:
            mantis = []
            for tmp in entries:
                mantis.extend(tmp.split(split_character))
            entries = mantis

        p['desc'].mantis = entries

    raw_table = []

    x = []
    x.append("Board-ID")
    for p in patchdescs:
        x.append(p)
    x.append("Comment")
    x.append("SW-version")
    x.append("Attachment")
    x.append("Location")
    raw_table.append(x)

    for b in boards:
        x = []

        x.append(b)

        for p in b.get_patchstatus():
            x.append(p)

        x.append(b.comment)

        if (b.swversion):
            x.append(b.swversion)
        else:
            x.append("")

        if b.attachment:
            x.append(b.attachment)
        else:
            x.append("")

        x.append(b.get_location())

        raw_table.append(x)

    table = []
    for col_counter in range(len(raw_table[0])):
        x = []
        for row in raw_table:
            x.append(row[col_counter])
        table.append(x)

    return my_render_to_response("tracker/boards.html", {
        'boardclass': boardclass,
        'boards': boards,
        'patchdescs': patchdescs,
        'board_table': table,
    }, request)


def board(request, board_id=''):
    board = Board.objects.get(id=board_id)
    events = Event.objects.filter(boardid=board_id)
    patches = Patch.objects.filter(classid=board.classid)
    boardstates = BoardStatus.objects.filter(boardid=board_id)
    locations = Location.objects.filter(boardid=board_id)

    eventform = EventForm()
    locationform = LocationForm()

    all_patches = board.get_all_patches()

    states = []
    for s in boardstates:
        s_patches = s.get_patches()
        p = []
        for cur_p in all_patches:
            if str(cur_p.id) in s_patches:
                p.append("Rev " + s_patches[str(cur_p.id)])
            else:
                p.append("-")
        states.append({'s':s, 'p':p, 'id': s.id})

    return my_render_to_response("tracker/board.html", {
        'board': board,
        'patches': patches,
        'states': states,
        'events': events,
        'eventform': eventform,
        'locationform': locationform,
        'locations': locations,
    }, request)


def patch(request, patch_id=''):
    patch = Patch.objects.get(id=patch_id)
    descs = PatchDesc.objects.filter(patchid=patch_id)
    boardclass = BoardClass.objects.get(id=patch.classid.id)

    username = get_username(request)

    return my_render_to_response("tracker/patch.html", {
        'username': username,
        'patch': patch,
        'descs': descs,
        'boardclass': boardclass
    }, request)


def do_register(request):
    username = get_username(request)
    if username:
        return HttpResponse("You are already logged in, no need for a new registration.")

    if request.method == 'POST':
        try:
            if not request.POST['password']:
                return my_render_to_response("error.html", {
                    'error': 'No password specified!',
                }, request)
        except KeyError:
            pass

        form = RegisterForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            password2 = form.cleaned_data['password2']
            email = form.cleaned_data['email']
            firstname = form.cleaned_data['firstname']
            lastname = form.cleaned_data['lastname']

            if password2 != password:
                return my_render_to_response("error.html", {
                    'error': 'Passwords don\'t match!',
                }, request)

            u = User.objects.create_user(username, email, password)
            u.firstname = firstname
            u.lastname = lastname
            try:
                u.save()
            except IntegrityError:
                return my_render_to_response("error.html", {
                    'error': 'User is already registered!',
                }, request)
            return my_render_to_response("registered.html", {
            }, request)
        return my_render_to_response("register.html", {
                'error': 'Invalid Data entered.',
                'form': form,
                'next': reverse(do_register),
            }, request)

    form = RegisterForm()

    return my_render_to_response("register.html", {
        'form': form,
        'next': reverse(do_register),
    }, request)


@login_required
def add_project(request):
    username = get_username(request)

    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name'].upper()
            desc = form.cleaned_data['desc']

            nr = re.match("^[Cc]?[Oo]?[Rr]?(\d+)", name)
            if nr:
                name = "COR" + str(nr.group(1))
            else:
                return my_render_to_response("error.html", {
                    'error': 'Invalid nr entered!',
                }, request)

            p = Project(name=name, desc=desc)
            p.save()
            g = Group(name=name)
            g.save()
            return HttpResponseRedirect(reverse(index))
        else:
            return my_render_to_response("error.html", {
                'error': 'Invalid data entered!',
            }, request)

    form = ProjectForm()

    return my_render_to_response("tracker/new_project.html", {
        'form': form,
        'username': username,
    }, request)


@login_required
def edit_project(request, project_id):
    username = get_username(request)

    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name'].upper()
            desc = form.cleaned_data['desc']

            nr = re.match("^[Cc]?[Oo]?[Rr]?(\d+)", name)
            if nr:
                name = "COR" + str(nr.group(1))
            else:
                return my_render_to_response("error.html", {
                    'error': 'Invalid nr entered!',
                }, request)

            p = Project.objects.get(id=project_id)
            g = Group.objects.get(name=p.name)

            g.name = name
            g.save()

            p.name = name
            p.desc = desc
            p.save()

            return HttpResponseRedirect(reverse(index))
        else:
            return my_render_to_response("error.html", {
                'error': 'Invalid data entered!',
            }, request)

    project = Project.objects.filter(id=project_id)[0]
    form = ProjectForm(initial={
            'name': project.name,
            'desc': project.desc
    })

    return my_render_to_response("tracker/edit_project.html", {
        'project': project,
        'form': form,
        'username': username,
    }, request)


@login_required
def add_boardclass(request, project_id=''):
    username = get_username(request)

    if request.method == 'POST':
        form = BoardClassForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            desc = form.cleaned_data['desc']
            productnr = form.cleaned_data['productnr'].upper()
            revision = form.cleaned_data['revision']
            project = Project.objects.get(id=project_id)

            if (BoardClass.objects.filter(name=name).filter(revision=revision).filter(projectid=project)):
                return my_render_to_response("error.html", {
                    'error': 'BoardClass for project %s with name %s and revision %s already exists!' %
                             (project, name, revision),
                }, request)

            b = BoardClass(
                projectid=project,
                name=name,
                desc=desc,
                productnr=productnr, 
                revision=revision
            )
            b.save()

            return HttpResponseRedirect(reverse(index))
        else:
            return my_render_to_response("error.html", {
                'error': 'Invalid data entered!',
            }, request)

    project = Project.objects.get(id=project_id)
    form = BoardClassForm()

    return my_render_to_response("tracker/new_boardclass.html", {
        'project': project,
        'form': form,
        'username': username,
    }, request)


@login_required
def edit_boardclass(request, class_id=''):
    username = get_username(request)

PCBTracker/templates/base_skeleton.html
<!DOCTYPE html>
<html lang="en">
<head>

{% load staticfiles %}

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/qtip2/3.0.3/basic/jquery.qtip.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/qtip2/3.0.3/basic/jquery.qtip.min.css" type="text/css" rel="stylesheet" />

<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">

<script type="text/javascript" src="http://coffeescript.org/extras/coffee-script.js"></script>

<script type="text/coffeescript" src="{% static 'tracker.coffee' %}"></script>
<link rel="stylesheet" href="{% static 'tracker.css' %}">

<script language="JavaScript">
    $(document).ready( function() {
        $('.qtiptooltip[id="qtiptooltip"]').each( function() {
            $(this).qtip({
                content: $(this).find('span.qtiptooltip'),
                hide: {
                    fixed: true,
                    delay: 50
                }
            });
        });
    });
</script>

{% block script %}{% endblock %}

<title>PCBTracker2</title>

<style type="text/css">
{% block styles %}{% endblock %}
</style>

<meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>
  <nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/main/">PCBTracker2</a>
    </div>

    <div class="navbar-btn navbar-right">
      {% if username %}
      <a class="btn btn-success some-margin" id="logout" href="/logout/">Logout {{ username }}</a>
      {% else %}
      <a class="btn btn-primary some-margin" id="login" href="/login/#">Login</a>
      <a class="btn btn-primary some-margin" href="/register/">Register</a>
      {% endif %}
    </div>

    <form class="navbar-form navbar-right" role="search" method="post" action="{% url 'PCBTracker.views.search' %}">
      {% csrf_token %}
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
        <input type="hidden" name="searchstring" value="True" />
        <input type="hidden" name="search_boardname" value="True" />
        <input type="hidden" name="search_projectname" value="True" />
        <input type="hidden" name="search_projectname" value="True" />
        <input type="hidden" name="search_serial" value="True" />
        <input type="hidden" name="search_productnr" value="True" />
        <input type="hidden" name="search_patchnr" value="True" />
      </div>
      <button type="submit" class="btn btn-default">Go</button>
    </form>
  </div>
  </nav>

  <div class="container-fluid" id="main">
  {% block content %}{% endblock %}
  </div>
</body>
</html>

PCBTracker/templates/login.html
{% extends "base_skeleton.html" %}

{% block content %}

<div class="panel panel-primary">
    <div class="panel-heading">Login</div>
    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <div class="form-group some-margin">
            <label for="id_username">Username</label>
            <input type="text" class="form-control" name="username" id="id_username">
        </div>
        <div class="form-group some-margin">
            <label for="id_password">Password</label>
            <input type="password" class="form-control" name="password" id="id_password">
        </div>
        <button type="submit" class="btn btn-default some-margin" value="submit">Login</button>
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
    {% if form.errors %}
    <div class="panel-footer">
        <span class="label label-danger">Your username and password didn't match. Please try again.</span>
    </div>
    {% endif %}
</div>

{% endblock %}

PCBTracker/templates/register.html
{% extends "base_skeleton.html" %}

{% block content %}

<div class="panel panel-primary">
    <div class="panel-heading">Register</div>

    <form method="post" action="{% url 'PCBTracker.views.do_register' %}">
        {% csrf_token %}
        <div class="form-group some-margin">
            <label for="id_username">Username *</label>
            <input type="text" class="form-control" name="username" id="id_username">
        </div>
        <div class="form-group some-margin">
            <label for="id_email">E-Mail *</label>
            <input type="email" class="form-control" name="email" id="id_email">
        </div>
        <div class="form-group some-margin">
            <label for="id_firstname">First name</label>
            <input type="text" class="form-control" name="firstname" id="id_firstname">
        </div>
        <div class="form-group some-margin">
            <label for="id_lastname">Last name</label>
            <input type="text" class="form-control" name="lastname" id="id_lastname">
        </div>
        <div class="form-group some-margin">
            <label for="id_password">Password *</label>
            <input type="password" class="form-control" name="password" id="id_password">
        </div>
        <div class="form-group some-margin">
            <label for="id_password2">Password (confirmation) *</label>
            <input type="password" class="form-control" name="password2"  id="id_password2">
        </div>
        <div class="some-margin">
            Note: Fields marked with a * are required.
        </div>
        <button type="submit" class="btn btn-default some-margin" value="Register">Register</button>
        <input type="hidden" name="next" value="{{ next }}" />
    </form>

    {% if error %}
    <div class="panel-footer">
        <span class="label label-danger">Error: {{ error }}</span>
    </div>
    {% endif %}
</div>

{% endblock %}